### ISSUE TITLE
Related posts are broken links.

### ISSUE THREAD

**Issue by fleeting** [mateoclarke/mateoclarke.github.io#1]
Just a heads up that related posts on your blog http://mateoclarke.com/blog/2015/05/22/notes-from-the-hunt/ are broken links due to an extra `/`. :monkey:

**Comment by mateoclarke** [comment]
wow, you're awesome! Thanks for catching that! I owe you a :beer:

**Comment by fleeting** [comment]
No problem. Love the post on your job hunt and digging the idea for the `What I Learned Yesterday` posts.
